import { ApolloClient, InMemoryCache } from "@apollo/client";

// @TODO attach the token from the cookies. This token is generated by JWT and includes the user id from a telegram message
export const client = new ApolloClient({
  uri: `${process.env.NEXT_PUBLIC_WEB_HOST}/api/graphql`,
  headers: {},
  cache: new InMemoryCache(),
});
