export type Styles = {
  button: string;
  button__content: string;
  "button__content--disabled": string;
  "button__content--loading": string;
  button__icon: string;
  "button__icon--left": string;
  "button__icon--on-left": string;
  "button__icon--right": string;
  button__loader: string;
  "button__loading-floating-border": string;
  "button--auto-size": string;
  "button--danger": string;
  "button--dark": string;
  "button--extra-small": string;
  "button--full-width": string;
  "button--gradient": string;
  "button--info": string;
  "button--inverted": string;
  "button--large": string;
  "button--light": string;
  "button--link": string;
  "button--loading": string;
  "button--medium": string;
  "button--outlined": string;
  "button--primary": string;
  "button--secondary": string;
  "button--small": string;
  "button--success": string;
  "button--text": string;
  "button-outline": string;
  "button-outline__icon": string;
  "button-outline_inverse": string;
  "button-outline_inverse-thin": string;
  "button-outline_large": string;
  "button-outline_medium": string;
  "button-outline--large": string;
  "button-outline--medium": string;
  "button-primary": string;
  "button-primary__icon": string;
  "button-primary__icon_left": string;
  "button-primary__icon_right": string;
  "button-primary_invert": string;
  "button-primary_large": string;
  "button-primary_medium": string;
  spin: string;
  "z-depth-0": string;
  "z-depth-1": string;
  "z-depth-1-half": string;
  "z-depth-2": string;
  "z-depth-3": string;
  "z-depth-4": string;
  "z-depth-5": string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
