apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      serviceAccountName: rapyd-secret-sa
      volumes:
        - name: rapyd-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-rapyd-secret"
      containers:
      - name: bot
        image: 111975705704.dkr.ecr.us-east-2.amazonaws.com/rapydbot/bot:latest
        volumeMounts:
        - name: rapyd-secret
          mountPath: "/mnt/secrets-store"
          readOnly: true

