apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secret-application
spec:
  provider: aws
  secretObjects:
    - secretName: application-api-key  # the k8s secret name
      type: Opaque
      data:
        - objectName: service-api-key # reference the corresponding parameter
          key: api_key
  parameters:
    objects: |
      - objectName: "service-api-key"  # the AWS secret
        objectType: "secretsmanager"

