apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-deployment
  labels:
    app: wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet
  template:
    metadata:
      labels:
        app: wallet
    spec:
      serviceAccountName: rapyd-secret-sa
      volumes:
        - name: rapyd-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-rapyd-secret"
      containers:
      - name: wallet
        image: 111975705704.dkr.ecr.us-east-2.amazonaws.com/rapydbot/wallet:latest
        ports:
        - containerPort: 30042
        volumeMounts:
        - name: rapyd-secret
          mountPath: "/mnt/secrets-store"
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
spec:
  selector:
    app: wallet
  type: ClusterIP
  ports:
    - port: 30042
      targetPort: 30042
