name: User Build
on: 
  push:
    branches:
      - master
    paths:
      - 'user/**'
      - '!user/package.json'
      - '!user/CHANGELOG.md'
jobs:
  User-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_AWS_ACTIONS }}

      # Login to AWS an ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Bump Version
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: 'user/CHANGELOG.md'
          tag-prefix: 'user-'
          skip-version-file: 'true' # ./package.json
          skip-on-empty: 'false'
          release-count: 0

      - name: Get Version
        id: appVersion
        run: echo "::set-output name=version::$(git tag --sort=-v:refname --list "user-[0-9]*" | head -n 1 | cut -c 6-)"

      - name: Build and Push to ECR public
        id: build-and-push
        uses: pahud/ecr-public-action@8cd826db40befb59b0cd0b60b22a7ba72d06a7f7
        with:
          dockerfile: user/Dockerfile
          context: user
          tags: |
            public.ecr.aws/l0y7w6p3/rapydbot/user:latest
            public.ecr.aws/l0y7w6p3/rapydbot/user:${{ steps.appVersion.outputs.version }}
            